from sttjenerator.models import registry

config = {
    "model": "faster_whisper",
    "model_path": "medium",
    "sample_rate": 16000,
    "sd_default_device": 7,
    "audio_np_or_file_path": "inputs/example.wav"
    # The stt-jenerator repo contains a short audio clip generated by the Kokoro TTS model.
    # Replace this with your own file.
    # Or you can also pass a numpy array to faster-whisper.
}

stt_generator = registry.get_model_class(config)
stt_generator.load()
output = stt_generator.generate()
for artifact in output.batch:
    print(
        "[%.2fs -> %.2fs] %s" 
        % 
        (artifact.item_extras["segment_start"], artifact.item_extras["segment_end"], artifact.data)
    )