from sttjenerator.models import registry

config = {
    "model": "faster_whisper",
    "model_path": "medium",
    "audio": "inputs/example.wav"
    # The stt-jenerator repo contains a short audio clip generated by the Kokoro TTS model.
    # Replace this with your own file.
    # Or you can also pass a numpy array.
}

stt_generator = registry.get_model_class(config)
stt_generator.load()
stt_generator.warmup()

output = stt_generator.generate()
for artifact in output.batch:
    print(
        "[%.2fs -> %.2fs] %s" 
        % 
        (artifact.item_extras["segment_start"], artifact.item_extras["segment_end"], artifact.data)
    )