# import torch
# from torch import autocast
import time
import datetime 
from typing import Tuple, List, Dict, Any

from faster_whisper import WhisperModel

from basejenerator.generator_output import GeneratorOutput
from basejenerator.artifacts.text_artifact import TextArtifact

from sttjenerator.models.registry import register_model
from sttjenerator.core.base_stt_generator import BaseSTTGenerator



@register_model("faster_whisper")
class FasterWhisper(BaseSTTGenerator):
    """
    Concrete implementation of BaseSTTGenerator for faster whisper.

    """

    def __init__(self, config):
        """
        Initializes the FasterWhisper generator.

        Args:
            config (dict): Configuration dictionary. Must include standard BaseClass
                           keys plus model-specific keys.
        """
        super().__init__(config)


    def load(self):
        """
        Abstract method to load the model into memory, and run any other initialisation
        steps needed.
        
        Subclasses must implement this to load the specific model and assign 
        it to `self.model`.
        """
        pass


    def prepare(self):
        """
        Reset lifecycle without tearing down the model - e.g., reset torch generators,
        clear cache, etc.
        """
        pass


    def warmup(self):
        """
        Initial inference run to create cache etc., mainly for benchmarking.
        """
        pass


    def generate(self) -> GeneratorOutput:
        """
        The public API that runs inference.

        Returns:
            GeneratorOutput        
        """
        return self.generate_impl()


    def generate_impl(self) -> Tuple[List[TextArtifact], Dict[str, Any]]:
        """
        Abstract method containing the core generation logic.

        Subclasses must implement this to run the inference and return artifacts and params.

        Returns:
            artifacts (List[Artifact]): A list of Artifact objects containing the artifacts generated by the model
            global_extras (Dict): Dictionary of any generation (i.e., not artifact specific) metadata
        """
        pass
    

    def teardown(self):
        """
        Purge the model from memory, empty cache, run garbage collector, etc. 
        Clears the slate to avoid bleed between inference runs.
        """
        pass


    def get_params_schema(self):
        """
        Returns Pydantic class listing params that the model can accept
        """
        pass

