import time
import datetime 
from typing import Tuple, List, Dict, Any, Literal
import gc

from faster_whisper import WhisperModel
from pydantic import BaseModel
import numpy as np

from basejenerator.generator_output import GeneratorOutput
from basejenerator.artifacts.text_artifact import TextArtifact

from sttjenerator.models.registry import register_model
from sttjenerator.core.base_stt_generator import BaseSTTGenerator



@register_model("faster_whisper")
class FasterWhisper(BaseSTTGenerator):
    """
    Concrete implementation of BaseSTTGenerator for faster whisper.
    """

    def __init__(self, config):
        """
        Initializes the FasterWhisper generator.

        Args:
            config (dict): Configuration dictionary. Must include standard BaseClass
                           keys plus model-specific keys.
        """
        super().__init__(config)
        if ("model_path" in self.config) and ("model_size" not in self.config):
            self.config["model_size"] = self.config["model_path"]
        if ("model_size" in self.config) and ("model_path" in self.config):
            self.config["model_path"] = self.config["model_size"]


    def load(self):
        """
        Abstract method to load the model into memory, and run any other initialisation
        steps needed.
        
        Subclasses must implement this to load the specific model and assign 
        it to `self.model`.
        """
        self.model = WhisperModel(self.config["model_path"])


    def prepare(self):
        """
        Reset lifecycle without tearing down the model - e.g., reset torch generators,
        clear cache, etc.
        """
        pass


    def warmup(self):
        """
        Initial inference run to create cache etc., mainly for benchmarking.
        """
        dummy_audio = np.zeros(16000, dtype=np.float32)
        self.model.transcribe(dummy_audio)


    def generate(self) -> GeneratorOutput:
        """
        The public API that runs inference.

        Returns:
            GeneratorOutput        
        """
        return self.generate_impl()


    def get_inference_kwargs(self):
        config = self.config.copy()

        ParamsSchema = self.get_params_schema()
        validated = ParamsSchema(**self.config)

        runtime_keys = self.get_runtime_params()

        kwargs = {
            k: v
            for k, v in validated.model_dump().items()
            if k in runtime_keys
        }

        return kwargs


    def generate_impl(self) -> Tuple[List[TextArtifact], Dict[str, Any]]:
        """
        Abstract method containing the core generation logic.

        Subclasses must implement this to run the inference and return artifacts and params.

        Returns:
            artifacts (List[Artifact]): A list of Artifact objects containing the artifacts generated by the model
            global_extras (Dict): Dictionary of any generation (i.e., not artifact specific) metadata
        """
        kwargs = self.get_inference_kwargs()

        segments, info = self.model.transcribe(
            **kwargs
        )
        artifacts = [
            TextArtifact(
                data = segment.text,
                item_extras = {
                    "segment_start": segment.start,
                    "segment_end": segment.end,
                    "pos_in_batch": i
                }
            )
            for i, segment in enumerate(segments)
        ]

        return GeneratorOutput(artifacts)
    

    def teardown(self):
        """
        Purge the model from memory, empty cache, run garbage collector, etc. 
        Clears the slate to avoid bleed between inference runs.
        """
        del self.model
        
        gc.collect()


    def get_runtime_params(self) -> set[str]:
        """
        Returns parameters in the model that, if changed, DO NOT require a teardown and 
        reload of the model.

        Returns:
            Set[str]: A set containing the names of the parameters.     
        """
        return (
            "audio",
            "language",
            "beam_size",
            "vad_filter",
            "temperature",
            "task",
        )


    def get_params_schema(self):
        """
        Returns Pydantic class listing params that the model can accept
        """
        class ParamsSchema(BaseModel):
            model_size: str = "medium"
            device: str = "cuda"
            compute_type: str = "float16"

            audio: str = ""
            language: str = "en"
            beam_size: int = 5 # higher = more accurate but slower
            vad_filter: bool = True
            temperature: float = 0.0
            task: Literal["transcribe", "translate"] = "transcribe" # "translate" to translate to English

        return ParamsSchema



